FROM nginx:alpine

# Copia TODO o conteúdo do repositório (onde está index.html, fotos/, css/, js/, etc.)
COPY . /usr/share/nginx/html/

# Config Nginx
COPY nginx-custom.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
