# Dockerfile.nginx
FROM nginx:alpine

# Copiar o conteúdo da pasta do site para a raiz do nginx
# IMPORTANT: aqui estamos copiando a pasta inteira RestauranteFrances-main/ -> /usr/share/nginx/html/
COPY RestauranteFrances-main/ /usr/share/nginx/html/

# Copiar config do nginx (crie nginx-custom.conf no mesmo diretório)
COPY nginx-custom.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
